name: scrape-atl-arborist-ddh
on:
  schedule:
    - cron: "14 8 * * *"  # daily 8:14 UTC (adjust as you wish)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm ci || npm i

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        run: npm run scrape

      - name: Commit GeoJSON (if changed)
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@users.noreply.github.com"
          git add docs/data/atl_arborist_ddh.geojson data/geocode-cache.json || true
          git diff --quiet && echo "No changes" || git commit -m "Update arborist DDH GeoJSON"
          git push
